-- ts file was generated at discord.gg/25ms


local fenv = getfenv()
fenv._RuytAsZkHkWD = "This file was protected with MoonSec V3"
wait()
fenv.MoonSec_StringsHiddenAttr = true
local _ = not game:IsLoaded()
game.Loaded:Wait()
local _call9 = game:GetService("Players")
Vector3.new(- 0, - 0, - 0)
fenv.Notify = function(...)
    local _13_vararg1, _13_vararg2, _13_vararg3 = ...
    local _call15 = Instance.new("ScreenGui")
    local _call17 = Instance.new("Frame", _call15)
    local _call19 = Instance.new("TextLabel", _call17)
    local _call21 = Instance.new("TextLabel", _call17)
    _call15.Name = "NotificationOof"
    _call15.Parent = game.CoreGui
    _call17.Name = "MainFrame"
    _call17.BackgroundColor3 = Color3.new(- 0.156863, - 0.156863, - 0.156863)
    _call17.BorderSizePixel = - 0
    _call17.Position = UDim2.new(- 1, - 5, - 0, - 50)
    _call17.Size = UDim2.new(- 0, - 330, - 0, - 100)
    _call19.BackgroundColor3 = Color3.new(- 0, - 0, - 0)
    _call19.BackgroundTransparency = - 0.89999997615814
    _call19.Size = UDim2.new(- 1, - 0, - 0, - 30)
    _call19.Font = Enum.Font.SourceSansSemibold
    _call19.Text = _13_vararg1
    _call19.TextColor3 = Color3.new(- 255, - 0, - 255)
    _call19.TextSize = - 25
    _call21.BackgroundColor3 = Color3.new(- 0, - 0, - 0)
    _call21.BackgroundTransparency = - 1
    _call21.Position = UDim2.new(- 0, - 0, - 0, - 30)
    _call21.Size = UDim2.new(- 1, - 0, - 1, - 30)
    _call21.Font = Enum.Font.SourceSans
    _call21.Text = _13_vararg2
    _call21.TextColor3 = Color3.new(- 255, - 0, - 255)
    _call21.TextSize = - 15
    wait(- 0.1)
    _call17:TweenPosition(UDim2.new(- 1, - 330, - 0, - 50), "Out", "Sine", - 0.5)
    wait(_13_vararg3)
    local _ = _13_vararg3 + 0.028981876501116787
    _call17:TweenPosition(UDim2.new(- 1, - 5, - 0, - 50), "Out", "Sine", - 0.5)
    wait(- 10)
    _call15:Destroy()
end
task.spawn(function(...)
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    local _ = not game:IsLoaded()
    task.wait()
    game:IsLoaded()
    error("internal 542: <25ms: infinitelooperror>")
end)
task.spawn(function(...)
    task.wait()
    CHECKIF(game:IsLoaded())
    local _callcloneref608 = cloneref(game:GetService("Stats"))
    _callcloneref608:GetTotalMemoryUsageMb()
    cloneref(game:GetService("RunService")).Stepped:Connect(function(...)
        Random.new():NextNumber(- 10, - 10)
    end)
    hookmetamethod(game, "__namecall", function(...)
        getnamecallmethod()
        local _ = not checkcaller()
        error("line 1: attempt to call a nil value")
    end)
    hookfunction(_callcloneref608.GetTotalMemoryUsageMb, function(...)
        CHECKIF(checkcaller())
    end)
end)
task.spawn(function(...)
    task.wait()
    CHECKIF(game:IsLoaded())
    local _callcloneref638 = cloneref(game:GetService("Stats"))
    _callcloneref638:GetMemoryUsageMbForTag(Enum.DeveloperMemoryTag.Gui)
    cloneref(game:GetService("RunService")).Stepped:Connect(function(...)
        Random.new():NextNumber(- 0.1, - 0.1)
    end)
    hookmetamethod(game, "__namecall", function(...)
        getnamecallmethod()
        local _ = not checkcaller()
        error("line 1: attempt to call a nil value")
    end)
    hookfunction(_callcloneref638.GetMemoryUsageMbForTag, function(...)
        local _ = not checkcaller()
    end)
end)
local _callcloneref666 = cloneref(game:GetService("CoreGui"))
game:GetService("ContentProvider"):PreloadAsync({
    [1] = _callcloneref666,
}, function(...)
    local _671_vararg1 = ...
    local _ = not _671_vararg1:find("rbxassetid://")
end)
for _677, _677_2 in pairs(game:GetDescendants()) do
    CHECKIF(_677)
    CHECKIF(_677_2:IsA("ImageLabel"))
    CHECKIF(_677_2.Image:find("rbxassetid://"))
    CHECKIF(_677_2:IsDescendantOf(_callcloneref666))
end
fenv.randomizeTable = function(...)
    local _685_vararg1 = ...
    local _ = # _685_vararg1
    error("internal 711: attempt to compare number < boolean")
end
hookmetamethod(game, "__namecall", function(...)
    local _callgetnamecallmethod689 = getnamecallmethod()
    local _ = not checkcaller()
    local _ = _callgetnamecallmethod689 ~= "preloadAsync"
    local _ = _callgetnamecallmethod689 ~= "PreloadAsync"
    error("line 1: attempt to call a nil value")
end)
hookfunction(cloneref(game:GetService("ContentProvider")).PreloadAsync, function(...)
    local _ = not checkcaller()
    error("line 1: attempt to call a nil value")
end)
local _ = game.IsDescendantOf
hookmetamethod(game, "__namecall", function(...)
    getnamecallmethod()
    local _ = not checkcaller()
    error("line 1: attempt to call a nil value")
end)
hookfunction(nil, function(...)
    error("line 1: attempt to call a nil value")
end)
cloneref(game:GetService("RunService")).Stepped:Connect(function(...)

end)
_call9.PlayerRemoving:Connect(function(...)
    local _717_vararg1 = ...
    local _ = _717_vararg1 == _call9.LocalPlayer
    game:Shutdown()
end)
game:GetService("RunService").Heartbeat:Connect(function(...)
    local _ = not _call9.LocalPlayer
end)
local _LocalPlayer731 = game:GetService("Players").LocalPlayer
_LocalPlayer731.CharacterAdded:Connect(function(...)
    local _735_vararg1 = ...
    game:GetService("RunService").Heartbeat:Wait()
    CHECKIF(_735_vararg1:FindFirstChildOfClass("Humanoid"))
    game:GetService("RunService").Heartbeat:Wait()
    CHECKIF(_735_vararg1:FindFirstChildOfClass("Humanoid").RootPart)
    local _call755 = game:GetService("RunService").Heartbeat:Connect(function(...)
        local _ = _LocalPlayer731.Character
    end)
    _LocalPlayer731.Character:FindFirstChildOfClass("Humanoid").RootPart:GetPropertyChangedSignal("CFrame"):Connect(function(...)
        local _RootPart774 = _LocalPlayer731.Character:FindFirstChildOfClass("Humanoid").RootPart
        _RootPart774.CFrame = _Character757:FindFirstChildOfClass("Humanoid").RootPart.CFrame
        game:GetService("RunService").Heartbeat:Wait()
    end)
    _LocalPlayer731.Character:FindFirstChildOfClass("Humanoid").Died:Connect(function(...)
        _call755:Disconnect()
    end)
end)
_LocalPlayer731.CharacterRemoving:Connect(function(...)
    _call755:Disconnect()
end)
local _call799 = game:GetService("RunService").Heartbeat:Connect(function(...)
    local _ = _LocalPlayer731.Character
end)
_LocalPlayer731.Character:FindFirstChildOfClass("Humanoid").RootPart:GetPropertyChangedSignal("CFrame"):Connect(function(...)
    local _RootPart818 = _LocalPlayer731.Character:FindFirstChildOfClass("Humanoid").RootPart
    _RootPart818.CFrame = _Character801:FindFirstChildOfClass("Humanoid").RootPart.CFrame
    game:GetService("RunService").Heartbeat:Wait()
end)
_LocalPlayer731.Character:FindFirstChildOfClass("Humanoid").Died:Connect(function(...)
    _call799:Disconnect()
end)
local _callgetrawmetatable833 = getrawmetatable(game)
fenv.grm = _callgetrawmetatable833
setreadonly(_callgetrawmetatable833, false)
local __namecall835 = _callgetrawmetatable833.__namecall
fenv.old = __namecall835
newcclosure(function(...)
    local _call837 = __namecall835(...)
    return _call837
end)
_callgetrawmetatable833.__namecall = function(...)
    local _call841 = __namecall835(...)
    return _call841
end
local _ = game:GetService("Players").LocalPlayer
hookmetamethod(game, "__index", function(...)
    CHECKIF(checkcaller())
    error("line 1: attempt to call a nil value")
end)
game.DescendantAdded:Connect(function(...)
    local _851_vararg1 = ...
    local _ = not _851_vararg1.ClassName:find("Body")
end)
local _Torso859 = game.Players.LocalPlayer.Character.Torso
_Torso859.Anchored = false
wait(- 0.1)
local _Torso863 = game.Players.LocalPlayer.Character.Torso
_Torso863.Anchored = false
wait(- 0.1)
local _Torso867 = game.Players.LocalPlayer.Character.Torso
_Torso867.Anchored = false
wait(- 0.1)
local _Torso871 = game.Players.LocalPlayer.Character.Torso
_Torso871.Anchored = false
wait(- 0.1)
local _Torso875 = game.Players.LocalPlayer.Character.Torso
_Torso875.Anchored = false
wait(- 0.1)
local _Torso879 = game.Players.LocalPlayer.Character.Torso
_Torso879.Anchored = false
wait(- 0.1)
local _Torso883 = game.Players.LocalPlayer.Character.Torso
_Torso883.Anchored = false
wait(- 0.1)
local _Torso887 = game.Players.LocalPlayer.Character.Torso
_Torso887.Anchored = false
wait(- 0.1)
local _Torso891 = game.Players.LocalPlayer.Character.Torso
_Torso891.Anchored = false
wait(- 0.1)
local _Torso895 = game.Players.LocalPlayer.Character.Torso
_Torso895.Anchored = false
wait(- 0.1)
local _Torso899 = game.Players.LocalPlayer.Character.Torso
_Torso899.Anchored = false
wait(- 0.1)
error("internal 542: <25ms: infinitelooperror>")
